---
title: "Guia Rápido Para Funções do Git"
author: Vinícius Riffel
date: June 28, 2019
papersize: a4
geometry: [bottom=1cm, left=2in, right=1.5in, top=2.5in]
output:
 pdf_document:
   number_sections: true
   template: default
documentclass: article
fontsize: 12pt
header-includes:
 - \newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}
 - \newcommand{\tab}[1]{\hspace{.2\textwidth}\rlap{#1}}
 - \usepackage[brazilian]{babel}
 - \usepackage[utf8]{inputenc}
 - \usepackage{graphicx}
 - \usepackage{latexsym,amsmath,amsfonts,amssymb}
 - \usepackage[longnamesfirst,sectionbib]{natbib}
 - \usepackage{amsmath}
 - \usepackage{amsfonts}
 - \usepackage{amssymb}
 - \usepackage{hyperref}
 - \usepackage{blindtext}
 - \usepackage{xcolor}
 - \usepackage{lipsum}
 - \usepackage{ntheorem}
 - \usepackage{mdframed}

 - \addtolength{\headsep}{-80pt}
 - \addtolength{\textwidth}{100pt}
 - \addtolength{\hoffset}{-50pt}
 - \makeindex
---
```{r echo = FALSE}
library(rmarkdown)
codigo1 <- "ssh-keygen -t rsa -b 4096 -C viniciusricardoriffel@gmail.com"
codigo2 <- "eval \\$(ssh-agent -s)"
codigo3 <- "ssh-add ~/.ssh/id\\_ra"
codigo4 <- "xclip -sel clip < ~/.ssh/id\\_rsa.pub"
```
\begin{abstract}
Aqui voc\^e encontrar\'a um pequeno guia com as fun\c{c}\~oes b\'asicas
do git. O objetivo \'e apenas apresentar as fun\c{c}\~oes, portanto, \'e
necess\'ario que o leitor possua conhecimentos pr\'evios no funcionamento do git, bem
como das fun\c{c}\~oes apresentadas. Assim, este material servir\'a apenas
como consulta para o usu\'ario.
\end{abstract}

\tableofcontents
\newpage

\section{Gerar Chave SSH}
Para gerar uma chave SSH no github siga os seguintes passos:
\begin{enumerate}
\item{Cole o código no terminal:} \\
\begin{mdframed}[backgroundcolor=blue!20]
`r codigo1`
\end{mdframed}
\item{Digite o \textit{password} e cole os seguintes codigos:} \\
\begin{mdframed}[backgroundcolor=blue!20]
`r codigo2` \\
`r codigo3`
\end{mdframed}
\item{Adicione a chave SSH no GitHub da seguinte forma}:
\subitem{Copie a chave SSH para o \textit{clipboard}} \\
\begin{mdframed}[backgroundcolor=blue!20]
\textit{sudo apt-get install xclip} \\
`r codigo4`
\end{mdframed}
\subitem{No GitHub, Settings, SSH, New SSH key, Key (cole a chave), Add.}
\end{enumerate}

\section{Pedir Ajuda}
\textbf{git help}

\section{Criar Repositório}
\textbf{git init}

\section{Adicionar Arquivo ao git}
\textbf{git add}
\subsection{\textbf{Opções}}

\subitem{\textbf{-n -\--dry-run}} \newline
  Não adiciona os arquivos de fato, apenas mostra se eles existem e/ou
  serão ignorados. \newline
  Use \textbf{-\--ignore-missing} para checar se algum arquivo será ignorado,
  estando no rastreado ou não.
\subitem{\textbf{-f -\--force}} \newline
  Força a adição dos arquivos.
\subitem{\textbf{-e -\--edit}} \newline
  Abre um editor de texto com um \textit{git diff}.
\subitem{\textbf{-u -\--update}} \newline
  Apenas modifica os arquivos já rastreados, não adiciona modifica arquivos
  não rastreados.
\subitem{\textbf{-\--ignore-errors}} \newline
  Se houver erro, não aborta o \textit{git add}.

\section{Commitar Mudanças}
\textbf{git commit}
\subsection{Opções}
\subitem{\textbf{-m <msg>}} \newline
  Coloca a mensagem do commit.
\subitem{\textbf{-a -\--all}} \newline
  Commita as alterações feitas nos arquivos já rastreados pelo git. \newline
\textit{Note que este comando NÃO commita arquivos que não estejam com status
"tracked"}.
\subitem{\textbf{-F -\--file=<file>}} \newline
  Commita com o conteúdo do arquivo como mensagem do commit.\newline
  - para standart input.
\subitem{\textbf{-\--author=<author>}} \newline
  Altera o autor.
\subitem{\textbf{-s -\--signoff}} \newline
  Assina o commit com uma chave GPG.
\subitem{\textbf{-\--date=<date>}} \newline
  Altera a data.
\subitem{\textbf{-\--amend}} \newline
  Altera algum argumento do último commit anterior.
  Por padrão é o argumento a ser alterado é a mensagem.
\subitem{\textbf{-q -\--quiet}} \newline
  Suprime o print dos outputs.

\section{Adicionar repositório Remoto}
\textbf{git remote add}
\subitem{\textbf{-v -\--verbose}} \newline
  Mostra todas as urls remotas conectadas.

\section{Puxar Alteração do Repositório Remoto}
\textbf{git pull}

\section{Enviar os Arquivos Para os Repositórios Remoto}
\textbf{git push}
\subsection{Opções}

\subitem{\textbf{-n -\--dry-run}} \newline
  Faz tudo, mas não envia as alterações.
\subitem{\textbf{-d -\--delete}}\newline
  Deleta arquivos especificados de um repositório remoto.
\subitem{\textbf{-f -\--force}}\newline
  Força o push.

\section{Clonar Repositório}
\textbf{git clone}
\subitem{\textbf{-b <name>-\-- origin <name>}}
  Clone trocando o nome do remote. Por padrão, o nome é \textit{origin}.

\section{Ver Commits Anteriores}
\textbf{git log}

\section{Navegar Pelo Histórico}
\textbf{git checkout <commit>}

\section{Status dos arquivos}
\textbf{git status}
\subsection{Opções}

\subitem{\textbf{-u[<mode>] -\--untracked-files[=<mode>]}} \newline
  Os modos são:
  \subitem{\textit{no}}: Não mostra arquivos não rastreados.
  \subitem{\textit{normal}}: Mostra arquivos não rastreados e diretórios.
  \subitem{\textit{all}}: Mostra arquivos em diretórios não rastreados.

\section{Corrigindo erros}
\textbf{git revert <commit>}
o **git revert** faz oposto do **git commit**.
\subsection{Opções}
\subitem{\textbf{-e -\--edit}} \newline
  Argumento padrão se estiver usando um terminal, permite alterar a
  mensagem do commit.
\subitem{\textbf{-s -\--signoff}} \newline
  Ver **git commit**
